In [2]:

import gym 
import itertools 
import matplotlib 
import matplotlib.style 
import numpy as np 
import pandas as pd 
import sys 
  
  
from collections import defaultdict 
import plotting 
  
matplotlib.style.use('ggplot') 
%matplotlib inline

In [ ]:
# !{sys.executable} -m pip uninstall path

In [3]:
""" Retreiving MOOC Dataset """

ds_mooc = pd.read_excel('E:\\Work\\Priyanka\Datasets\\Consolidated Dataset.xlsx')
ds_mooc.head(14)

,course_id,course_title,course_duration,level_of_study,is_paid,price,students_enrolled,student_rating,course_url
0,1070968,Ultimate Investment Banking Course,1.5,All Levels,True,200,2147,4.7,https://www.udemy.com/ultimate-investment-bank...
1,1113822,Complete GST Course & Certification - Grow You...,39.0,All Levels,True,75,2792,4.7,https://www.udemy.com/goods-and-services-tax/
2,1006314,Financial Modeling for Business Analysts and C...,2.5,Intermediate Level,True,45,2174,4.5,https://www.udemy.com/financial-modeling-for-b...
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,3.0,All Levels,True,95,2451,4.7,https://www.udemy.com/complete-excel-finance-c...
4,1011058,How To Maximize Your Profits Trading Options,2.0,Intermediate Level,True,200,1276,4.8,https://www.udemy.com/how-to-maximize-your-pro...
5,192870,Trading Penny Stocks: A Guide for All Levels I...,3.0,All Levels,True,150,9221,4.7,https://www.udemy.com/trading-penny-stocks-a-g...
6,739964,Investing And Trading For Beginners: Mastering...,1.0,Beginner Level,True,65,1540,4.8,https://www.udemy.com/investing-and-trading-fo...
7,403100,"Trading Stock Chart Patterns For Immediate, Ex...",2.5,All Levels,True,95,2917,4.8,https://www.udemy.com/trading-chart-patterns-f...
8,476268,Options Trading 3 : Advanced Stock Profit and ...,2.5,Expert Level,True,195,5172,4.7,https://www.udemy.com/day-trading-stock-option...
9,1167710,The Only Investment Strategy You Need For Your...,1.0,All Levels,True,200,827,4.7,https://www.udemy.com/the-only-investment-stra...
10,592338,Forex Trading Secrets of the Pros With Amazon'...,5.0,All Levels,True,200,4284,4.6,https://www.udemy.com/trading-with-amazons-aws...
11,975046,Trading Options With Money Flow,1.0,All Levels,True,200,1380,4.7,https://www.udemy.com/trading-options-using-mo...
12,742602,Financial Management Risk and Return For Secur...,1.5,All Levels,True,30,3607,4.6,https://www.udemy.com/risk-and-return-finance/
13,794151,Forex Trading Course: Work Smarter Not Harder ...,2.0,All Levels,True,195,4061,4.3,https://www.udemy.com/the-complete-trading-cou...

In [4]:
""" Retreiving User Profile Data from Excel """

df = pd.read_excel('E:\\Work\\Priyanka\\Datasets\\user_profile_ds.xlsx')
df.tail(14)

,Timestamp,name,email_address,is_working_pro,degree,university,field_major,company,designation,area_of_interest,experience_level,course_duration,course_type,motive_to_study
33,2021-02-22 18:48:18.235,Deepika,deepikasivaraman.ds@gmail.com,No,Masters,WCC,Computer Science,NaN,NaN,Graphic Design,Beginner,NaN,Free,Explore new ideas
34,2021-02-22 18:53:12.465,FauziyA,fauziyarokaiya97@gmail.com,No,Masters,Wcc,HR,NaN,NaN,Hr,Novice,NaN,Paid,Interest
35,2021-02-22 19:00:32.961,Deepika jothi,s.deepikajothi@gmail.com,No,Masters,Madras university,IT,NaN,NaN,Graphic Design,Intermediate,NaN,Free,I am starting a business so need to be good
36,2021-02-22 19:04:19.786,Swathi,swathimmani@gmail.com,Yes,NaN,NaN,NaN,Cognizant,Software Tester,"Computer Programming, Data Science",Intermediate,NaN,Free,To improve the existing knowledge and to explo...
37,2021-02-22 19:05:29.508,Chelsea Rajanayagam,chelseagift1306@gmail.com,Yes,NaN,NaN,NaN,Cognizant technology solutions,Software Tester,"Business, Computer Programming, Data Science, ...",Intermediate,NaN,Free,Improve knowledge
38,2021-02-22 19:10:23.274,Nandhini,nandhu.356@gmail.com,Yes,NaN,NaN,NaN,Amazon,Software Tester,Business,Novice,NaN,Free,To study basic of business
39,2021-02-22 19:11:06.962,Aishwarya Srinivasan,aishwaryasrinivasan173@gmail.com,Yes,NaN,NaN,NaN,Intellect design arena limited,Software Developer,Computer Programming,Beginner,NaN,Free,To gain more knowledge in other areas
40,2021-02-22 19:13:39.049,Rita,ritafelicity4@gmail.com,No,Masters,Women's Christian College,Computer science,NaN,NaN,"Computer Programming, Web Development, Graphic...",Intermediate,NaN,Free,Gain knowledge
41,2021-02-22 19:20:39.447,Krisha T Panchamia,krisha25254@gmail.com,Yes,NaN,NaN,NaN,Digital Biz,Salesforce Developer,"Data Science, Graphic Design",Novice,NaN,Free,Gain a little insight and learn .
42,2021-02-22 19:55:41.585,Pavethra,pavethraravi@gmail.com,Yes,NaN,NaN,NaN,Amazon,Software Tester,"Business, Web Development",Novice,NaN,Free,To excell in skills that I'm Passinate about a...
43,2021-02-22 21:07:57.126,Anthea,anthea.sas@gmail.com,Yes,NaN,NaN,NaN,SaneForce,Software Developer,"Computer Programming, Web Development",Intermediate,NaN,Free,To enrich more information
44,2021-02-22 22:12:38.140,DEVIPRIYA P,devipriya2594@gmail.com,No,M.Phil,UNIVERSITY OF MADRAS,BIG DATA ANALYSIS,NaN,NaN,"Business, Computer Programming, Data Science, ...",Novice,NaN,Free,The best hacker only Know how to build the bes...
45,2021-02-22 22:41:58.587,Sukitha,evelyin74@gmail.com,Yes,NaN,NaN,NaN,3i infotech,Software Tester,Automation testing,Intermediate,NaN,Free,To gain updated knowledge in my field
46,2021-02-23 17:48:32.434,V.Meenakshi,meenakshi.research@gmail.com,No,Doctrate,University of Madras,Computer,NaN,NaN,"Business, Data Science, Web Development",Beginner,NaN,"Paid, Free",Upskill

In [5]:
# Data Pre-processing begins here.

""" Replacing certain attribute values to their numerical equivalents """

def replace_is_paid(value):
    if value:
        return 1
    else:
        return 0

def replace_level_of_study(value):
    if "All Levels" in value:
        return 3
    elif "Intermediate" in value:
        return 1
    elif "Beginner" in value:
        return 0
    elif "Expert" in value:
        return 2
   
ds_mooc['is_paid'] = ds_mooc['is_paid'].apply(replace_is_paid, 1)
ds_mooc['level_of_study'] = ds_mooc['level_of_study'].apply(replace_level_of_study, 1)
ds_mooc.head()

,course_id,course_title,course_duration,level_of_study,is_paid,price,students_enrolled,student_rating,course_url
0,1070968,Ultimate Investment Banking Course,1.5,3.0,1,200,2147,4.7,https://www.udemy.com/ultimate-investment-bank...
1,1113822,Complete GST Course & Certification - Grow You...,39.0,3.0,1,75,2792,4.7,https://www.udemy.com/goods-and-services-tax/
2,1006314,Financial Modeling for Business Analysts and C...,2.5,1.0,1,45,2174,4.5,https://www.udemy.com/financial-modeling-for-b...
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,3.0,3.0,1,95,2451,4.7,https://www.udemy.com/complete-excel-finance-c...
4,1011058,How To Maximize Your Profits Trading Options,2.0,1.0,1,200,1276,4.8,https://www.udemy.com/how-to-maximize-your-pro...

In [6]:
# Assigning numerical values to Area of Interest to get better correlation

area_of_interest = {}


def get_areas_of_interest():
    counter = 0
    for interest in df['area_of_interest'].unique():
        if "," in interest:
            for i in interest.split(','):
                if i.strip() not in area_of_interest.keys():
                    area_of_interest[i.strip()] = counter
                    counter += 1
        else:
            if interest.strip() not in area_of_interest.keys():
                area_of_interest[interest.strip()] = counter
                counter += 1

get_areas_of_interest()

def replace_area_of_interest(value):
    list_values = []
    
    if "," in value:
        for interest in value.split(','):
            list_values.append(area_of_interest[interest.strip()])
    else:
        list_values.append(area_of_interest[value.strip()])
    
    return list_values

In [7]:
df['area_of_interest'] = df['area_of_interest'].apply(replace_area_of_interest, convert_dtype = str)
df.tail(14)

,Timestamp,name,email_address,is_working_pro,degree,university,field_major,company,designation,area_of_interest,experience_level,course_duration,course_type,motive_to_study
33,2021-02-22 18:48:18.235,Deepika,deepikasivaraman.ds@gmail.com,No,Masters,WCC,Computer Science,NaN,NaN,[3],Beginner,NaN,Free,Explore new ideas
34,2021-02-22 18:53:12.465,FauziyA,fauziyarokaiya97@gmail.com,No,Masters,Wcc,HR,NaN,NaN,[8],Novice,NaN,Paid,Interest
35,2021-02-22 19:00:32.961,Deepika jothi,s.deepikajothi@gmail.com,No,Masters,Madras university,IT,NaN,NaN,[3],Intermediate,NaN,Free,I am starting a business so need to be good
36,2021-02-22 19:04:19.786,Swathi,swathimmani@gmail.com,Yes,NaN,NaN,NaN,Cognizant,Software Tester,"[1, 2]",Intermediate,NaN,Free,To improve the existing knowledge and to explo...
37,2021-02-22 19:05:29.508,Chelsea Rajanayagam,chelseagift1306@gmail.com,Yes,NaN,NaN,NaN,Cognizant technology solutions,Software Tester,"[5, 1, 2, 4]",Intermediate,NaN,Free,Improve knowledge
38,2021-02-22 19:10:23.274,Nandhini,nandhu.356@gmail.com,Yes,NaN,NaN,NaN,Amazon,Software Tester,[5],Novice,NaN,Free,To study basic of business
39,2021-02-22 19:11:06.962,Aishwarya Srinivasan,aishwaryasrinivasan173@gmail.com,Yes,NaN,NaN,NaN,Intellect design arena limited,Software Developer,[1],Beginner,NaN,Free,To gain more knowledge in other areas
40,2021-02-22 19:13:39.049,Rita,ritafelicity4@gmail.com,No,Masters,Women's Christian College,Computer science,NaN,NaN,"[1, 4, 3]",Intermediate,NaN,Free,Gain knowledge
41,2021-02-22 19:20:39.447,Krisha T Panchamia,krisha25254@gmail.com,Yes,NaN,NaN,NaN,Digital Biz,Salesforce Developer,"[2, 3]",Novice,NaN,Free,Gain a little insight and learn .
42,2021-02-22 19:55:41.585,Pavethra,pavethraravi@gmail.com,Yes,NaN,NaN,NaN,Amazon,Software Tester,"[5, 4]",Novice,NaN,Free,To excell in skills that I'm Passinate about a...
43,2021-02-22 21:07:57.126,Anthea,anthea.sas@gmail.com,Yes,NaN,NaN,NaN,SaneForce,Software Developer,"[1, 4]",Intermediate,NaN,Free,To enrich more information
44,2021-02-22 22:12:38.140,DEVIPRIYA P,devipriya2594@gmail.com,No,M.Phil,UNIVERSITY OF MADRAS,BIG DATA ANALYSIS,NaN,NaN,"[5, 1, 2, 4, 3, 0, 9]",Novice,NaN,Free,The best hacker only Know how to build the bes...
45,2021-02-22 22:41:58.587,Sukitha,evelyin74@gmail.com,Yes,NaN,NaN,NaN,3i infotech,Software Tester,[10],Intermediate,NaN,Free,To gain updated knowledge in my field
46,2021-02-23 17:48:32.434,V.Meenakshi,meenakshi.research@gmail.com,No,Doctrate,University of Madras,Computer,NaN,NaN,"[5, 2, 4]",Beginner,NaN,"Paid, Free",Upskill

In [8]:
# Assign values to course title according to area of interest

def replace_courses_by_area_of_interest(value):
    relevant_course_list = []
    for i in range(0, len(area_of_interest)):
        for key in area_of_interest.keys():
            if key in value:
                relevant_course_list.append(area_of_interest[key])
    return relevant_course_list

ds_mooc.head(14)

,course_id,course_title,course_duration,level_of_study,is_paid,price,students_enrolled,student_rating,course_url
0,1070968,Ultimate Investment Banking Course,1.5,3.0,1,200,2147,4.7,https://www.udemy.com/ultimate-investment-bank...
1,1113822,Complete GST Course & Certification - Grow You...,39.0,3.0,1,75,2792,4.7,https://www.udemy.com/goods-and-services-tax/
2,1006314,Financial Modeling for Business Analysts and C...,2.5,1.0,1,45,2174,4.5,https://www.udemy.com/financial-modeling-for-b...
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,3.0,3.0,1,95,2451,4.7,https://www.udemy.com/complete-excel-finance-c...
4,1011058,How To Maximize Your Profits Trading Options,2.0,1.0,1,200,1276,4.8,https://www.udemy.com/how-to-maximize-your-pro...
5,192870,Trading Penny Stocks: A Guide for All Levels I...,3.0,3.0,1,150,9221,4.7,https://www.udemy.com/trading-penny-stocks-a-g...
6,739964,Investing And Trading For Beginners: Mastering...,1.0,0.0,1,65,1540,4.8,https://www.udemy.com/investing-and-trading-fo...
7,403100,"Trading Stock Chart Patterns For Immediate, Ex...",2.5,3.0,1,95,2917,4.8,https://www.udemy.com/trading-chart-patterns-f...
8,476268,Options Trading 3 : Advanced Stock Profit and ...,2.5,2.0,1,195,5172,4.7,https://www.udemy.com/day-trading-stock-option...
9,1167710,The Only Investment Strategy You Need For Your...,1.0,3.0,1,200,827,4.7,https://www.udemy.com/the-only-investment-stra...
10,592338,Forex Trading Secrets of the Pros With Amazon'...,5.0,3.0,1,200,4284,4.6,https://www.udemy.com/trading-with-amazons-aws...
11,975046,Trading Options With Money Flow,1.0,3.0,1,200,1380,4.7,https://www.udemy.com/trading-options-using-mo...
12,742602,Financial Management Risk and Return For Secur...,1.5,3.0,1,30,3607,4.6,https://www.udemy.com/risk-and-return-finance/
13,794151,Forex Trading Course: Work Smarter Not Harder ...,2.0,3.0,1,195,4061,4.3,https://www.udemy.com/the-complete-trading-cou...

In [9]:
#ds_mooc['course_title'] = ds_mooc['course_title'].apply(replace_courses_by_area_of_interest, 1)
ds_mooc.head()

,course_id,course_title,course_duration,level_of_study,is_paid,price,students_enrolled,student_rating,course_url
0,1070968,Ultimate Investment Banking Course,1.5,3.0,1,200,2147,4.7,https://www.udemy.com/ultimate-investment-bank...
1,1113822,Complete GST Course & Certification - Grow You...,39.0,3.0,1,75,2792,4.7,https://www.udemy.com/goods-and-services-tax/
2,1006314,Financial Modeling for Business Analysts and C...,2.5,1.0,1,45,2174,4.5,https://www.udemy.com/financial-modeling-for-b...
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,3.0,3.0,1,95,2451,4.7,https://www.udemy.com/complete-excel-finance-c...
4,1011058,How To Maximize Your Profits Trading Options,2.0,1.0,1,200,1276,4.8,https://www.udemy.com/how-to-maximize-your-pro...

In [10]:
# Segregating Paid and Free courses

df['course_type'] = df['course_type'].map({
    'Free': 0,
    'Paid': 1,
    'Paid, Free': 2
}.get)

# Assigning values based on experience level

df['experience_level'] = df['experience_level'].map({
    'Novice': 0,
    'Beginner': 1,
    'Intermediate': 2
}.get)

df.head()

,Timestamp,name,email_address,is_working_pro,degree,university,field_major,company,designation,area_of_interest,experience_level,course_duration,course_type,motive_to_study
0,2021-02-21 02:04:06.158,Suzannah,suzannahfarrar@gmail.com,Yes,NaN,NaN,NaN,SCB,Software Developer,[0],1,"1 month, 3 months",0,I just have too much time on my hands
1,2021-02-21 03:52:57.664,Dora,suzannahfarrar@outlook.com,No,Masters,Madras University,IT,NaN,NaN,"[1, 2]",0,NaN,2,Interest in Data Science
2,2021-02-21 17:13:43.183,Suganya Selvam,suganya.selvam1008@gmail.com,No,Bachelors,Women’s Christian college,Major,NaN,NaN,[3],0,NaN,0,I have interest in graphic design
3,2021-02-21 17:38:38.777,GRACE INBAVATHI,grace24.research@gmail.com,No,Masters,University of Madras,Computer Science,NaN,NaN,[4],2,NaN,0,.
4,2021-02-21 17:38:45.421,Sneha S,sneharrin@gmail.com,No,Bachelors,Wcc,Computer Science,NaN,NaN,"[1, 3]",1,NaN,0,To look more into the subject

In [231]:
df.tail(14)

,Timestamp,name,email_address,is_working_pro,degree,university,field_major,company,designation,area_of_interest,experience_level,course_duration,course_type,motive_to_study
33,2021-02-22 18:48:18.235,Deepika,deepikasivaraman.ds@gmail.com,No,Masters,WCC,Computer Science,NaN,NaN,[3],1,NaN,0,Explore new ideas
34,2021-02-22 18:53:12.465,FauziyA,fauziyarokaiya97@gmail.com,No,Masters,Wcc,HR,NaN,NaN,[8],0,NaN,1,Interest
35,2021-02-22 19:00:32.961,Deepika jothi,s.deepikajothi@gmail.com,No,Masters,Madras university,IT,NaN,NaN,[3],2,NaN,0,I am starting a business so need to be good
36,2021-02-22 19:04:19.786,Swathi,swathimmani@gmail.com,Yes,NaN,NaN,NaN,Cognizant,Software Tester,"[1, 2]",2,NaN,0,To improve the existing knowledge and to explo...
37,2021-02-22 19:05:29.508,Chelsea Rajanayagam,chelseagift1306@gmail.com,Yes,NaN,NaN,NaN,Cognizant technology solutions,Software Tester,"[5, 1, 2, 4]",2,NaN,0,Improve knowledge
38,2021-02-22 19:10:23.274,Nandhini,nandhu.356@gmail.com,Yes,NaN,NaN,NaN,Amazon,Software Tester,[5],0,NaN,0,To study basic of business
39,2021-02-22 19:11:06.962,Aishwarya Srinivasan,aishwaryasrinivasan173@gmail.com,Yes,NaN,NaN,NaN,Intellect design arena limited,Software Developer,[1],1,NaN,0,To gain more knowledge in other areas
40,2021-02-22 19:13:39.049,Rita,ritafelicity4@gmail.com,No,Masters,Women's Christian College,Computer science,NaN,NaN,"[1, 4, 3]",2,NaN,0,Gain knowledge
41,2021-02-22 19:20:39.447,Krisha T Panchamia,krisha25254@gmail.com,Yes,NaN,NaN,NaN,Digital Biz,Salesforce Developer,"[2, 3]",0,NaN,0,Gain a little insight and learn .
42,2021-02-22 19:55:41.585,Pavethra,pavethraravi@gmail.com,Yes,NaN,NaN,NaN,Amazon,Software Tester,"[5, 4]",0,NaN,0,To excell in skills that I'm Passinate about a...
43,2021-02-22 21:07:57.126,Anthea,anthea.sas@gmail.com,Yes,NaN,NaN,NaN,SaneForce,Software Developer,"[1, 4]",2,NaN,0,To enrich more information
44,2021-02-22 22:12:38.140,DEVIPRIYA P,devipriya2594@gmail.com,No,M.Phil,UNIVERSITY OF MADRAS,BIG DATA ANALYSIS,NaN,NaN,"[5, 1, 2, 4, 3, 0, 9]",0,NaN,0,The best hacker only Know how to build the bes...
45,2021-02-22 22:41:58.587,Sukitha,evelyin74@gmail.com,Yes,NaN,NaN,NaN,3i infotech,Software Tester,[10],2,NaN,0,To gain updated knowledge in my field
46,2021-02-23 17:48:32.434,V.Meenakshi,meenakshi.research@gmail.com,No,Doctrate,University of Madras,Computer,NaN,NaN,"[5, 2, 4]",1,NaN,2,Upskill

In [13]:
print(area_of_interest)

{'Data Structures and Algorithms': 0, 'Computer Programming': 1, 'Data Science': 2, 'Graphic Design': 3, 'Web Development': 4, 'Business': 5, 'Back end development': 6, 'Ui design & development': 7, 'Hr': 8, 'Network security and ethical hacking and analysis': 9, 'Automation testing': 10}

In [14]:
# Defining possible actions for given dataset

actions = []
for i in ds_mooc['course_title'].unique():
    actions.append(i)

In [187]:
# Defining rewards

def set_reward(action, user_area_of_interest):
    reward = 0
    
    new_split_arr = []
    for area in user_area_of_interest:
        if area in action:
            reward += 10
        else:
            new_split_arr += area.split(' ')
            new_course_arr = action.split(' ')

            for word in new_course_arr:
                if word in new_split_arr:
                    reward += 1

    if reward < 1:
        reward = -100
    else:
        reward += 10
    
    return reward

In [220]:
""" Applying our RL algorithm - Based on Q Learning and Epsilon Greedy techniques """

# Defining our attributes
# We use 'area of interest' from customer profile dataset and 'course title' and 'ratings' from course dataset

class Q_Learning:
    def __init__(self, actions, learning_rate=0.08, reward_decay=0.1, e_greedy=0.92):
        # List of actions
        self.actions = actions
        # Learning rate
        self.lr = learning_rate
        # Value of gamma
        self.gamma = reward_decay
        # Value of epsilon
        self.epsilon = e_greedy
        # Creating full Q-table for all cells
        self.q_table = pd.DataFrame(columns=self.actions, dtype=np.float64)
        # Creating Q-table for cells of the final route
        self.q_table_final = pd.DataFrame(columns=self.actions, dtype=np.float64)
    
    def choose_action(self, observation):
            # Checking if the state exists in the table
            self.check_state_exist(observation)
            # Selection of the action - 90 % according to the epsilon == 0.9
            # Choosing the best action
            if np.random.uniform() < self.epsilon:
                state_action = self.q_table.loc[observation, :]
                state_action = state_action.reindex(np.random.permutation(state_action.index))
                action = state_action.idxmax()
            else:
                # Choosing random action - left 10 % for choosing randomly
                action = np.random.choice(self.actions)
            return action
        
    def learn(self, state, action, reward, next_state, user_area_of_interest):
        # Checking if the next step exists in the Q-table
        self.check_state_exist(next_state)

        # Current state in the current position
        q_predict = self.q_table.loc[state, action]

        # Checking if the next state is free or it is obstacle or goal
        if user_area_of_interest not in next_state:
            q_target = reward + self.gamma * self.q_table.loc[next_state, :].max()
        else:
            q_target = reward

        # Updating Q-table with new knowledge
        learn_index =(self.q_table.loc[state, action]) + (self.lr * (q_target - q_predict))
        self.q_table.loc[state, action] += learn_index

        return learn_index

    # Adding to the Q-table new states
    def check_state_exist(self, state):
        if state not in self.q_table.index:
            self.q_table = self.q_table.append(
                pd.Series(
                    [0]*len(self.actions),
                    index=self.q_table.columns,
                    name=state,
                )
            )

    # Printing the Q-table with states
    def print_q_table(self):
        # Getting the coordinates of final route from env.py
        e = final_states()

        # Comparing the indexes with coordinates and writing in the new Q-table values
        for i in range(len(e)):
            state = str(e[i])  # state = '[5.0, 40.0]'
            # Going through all indexes and checking
            for j in range(len(self.q_table.index)):
                if self.q_table.index[j] == state:
                    self.q_table_final.loc[state, :] = self.q_table.loc[state, :]

        print()
        print('Length of final Q-table =', len(self.q_table_final.index))
        print('Final Q-table with values from the final route:')
        print(self.q_table_final)

        print()
        print('Length of full Q-table =', len(self.q_table.index))
        print('Full Q-table:')
        print(self.q_table)

In [221]:
# Calling on our methods defined above
from qpath import final_states
from qpath import Environment


RL = Q_Learning(actions=actions)

user_area_of_interest = ["Data Science and Analysis"]

In [222]:
# Testing model for 1 iteration

i = 0
chosen_action = RL.choose_action(i)
reward = set_reward(chosen_action, user_area_of_interest)
learn_index = RL.learn(i, chosen_action, reward, actions[i+1], ",".join(user_area_of_interest))

print("Testing sample: \n")
print("Action: ", chosen_action)
print("Reward: ", reward)
print("Learn Index: ", learn_index)

Testing sample:

Action:  Profit and Loss Account for bankers and credit analysts
Reward:  12
Learn Index:  0.96

In [230]:
# Agent picks out courses

print("Running agent...")

recommendations = {}

i = 0
for episode in range(0, 100):
    
    
    while True:
        
        if (i + 1) < (len(actions) - 1):
            chosen_action = RL.choose_action(i)
            reward = set_reward(chosen_action, user_area_of_interest)
            learn_index = RL.learn(i, chosen_action, reward, actions[i+1], ",".join(user_area_of_interest))

            if learn_index > 0:
                if chosen_action not in recommendations.values():
                    recommendations[reward] = chosen_action
                    i += 1
                    # recommendations.append(chosen_action)
                    # print("Course chosen: ", chosen_action)
                break
            i += 1
            
            
# Optimising Suggestions to the results with the most rewards
# print(recommendations)
if len(recommendations) > 10:
    while len(recommendations) > 10:
        min_reward = min(recommendations.keys())
        recommendations.remove(min_reward)

        
# Displaying our model's findings

print("\nFinal Recommendations: ")
j = 1
for val in recommendations.values():
    print(j, ". ", val)
    j += 1

Running agent...

Final Recommendations:
1 .  Foundations for Big Data Analysis with SQL
2 .  Learn Ajax and jquery with PHP
3 .  Data Analysis and Presentation Skills: the PwC Approach